name: Update RSS Feed

on:
  schedule:
    # Run daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write  # Allow pushing changes back to repo

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install dependencies
      run: uv sync
      
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run feed update
      run: uv run python update_feed.py
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push changes
      run: |
        git add data/gain_feed.xml data/gain_feed.duckdb
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update RSS feed - $(date -u +%Y-%m-%d)"
          git push
        fi
